In [ ]:
#create the tuple
#empty tuple
my_tuple = ()
print(my_tuple)

()


In [ ]:
#having same datatype
my_tuple = (2,3,4,5)
print(my_tuple)

(2, 3, 4, 5)


In [ ]:
#having different datatype
my_tuple1 = (1,1.25,'hello',1+3j)
print(my_tuple1)


(1, 1.25, 'hello', (1+3j))


In [ ]:
#nested_tuple
my_tuple2 = ('key', [1,2,3],[4,5,6])
print(my_tuple2)


('key', [1, 2, 3], [4, 5, 6])


In [ ]:
#tuple can be created without parentheses is called as packing
my_tuple = 3,4,'hello'
print(my_tuple)

#unpacking of a tuple
a,b,c = my_tuple
print(a)
print(b)
print(c)

(3, 4, 'hello')
3
4
hello


In [ ]:
a = {}
print(type(a))


<class 'dict'>


In [ ]:
a1 = set()
print(type(a1))

<class 'set'>


In [ ]:
a2 = {1,2,3}
print(a2)

{1, 2, 3}


In [ ]:
odd = {1,2,3,4}
odd.update([5,6,7])
print(odd)

odd.discard(4)
print(odd)

odd.remove(7)
print(odd)

odd.pop()
print(odd)

my_set = {4,5,6}
print(my_set)
my_set.clear()
print(my_set)

{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 5, 6, 7}
{1, 2, 3, 5, 6}
{2, 3, 5, 6}
{4, 5, 6}
set()


In [ ]:
my_dict = {1:'hello'}
print(type(my_dict))
print(my_dict)

<class 'dict'>
{1: 'hello'}


In [ ]:
A = {1,2,3,4,5,6}
B = {6,7,8,9,10}
print(A.union(B))
print(B.union(A))

print(A|B)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
A = {1,2,3,4,5,6}
B = {6,7,8,9,10}

print(A & B)

#set symmetry
print(A^B)

#set difference
print(A-B)


{6}
{1, 2, 3, 4, 5, 7, 8, 9, 10}
{1, 2, 3, 4, 5}


In [ ]:
my_dict = {}
print(my_dict)
print(type(my_dict))

my_dict1 = {1:'Cricket',2:'Football'}
print(my_dict1)

#nested_dictionary
my_dict2 = {1:{'name':'alex', 'age':24},2:{'name':'sam','age':22}}
print(my_dict2)

{}
<class 'dict'>
{1: 'Cricket', 2: 'Football'}
{1: {'name': 'alex', 'age': 24}, 2: {'name': 'sam', 'age': 22}}


In [ ]:
my_dict = {'name':'Jack', 'age':23}
print(my_dict['name'])
my_dict['age']=24
print(my_dict)

Jack
{'name': 'Jack', 'age': 24}


In [31]:
people = {1:{'name':"John",'age':25,'gender':'Male'},
          2:{'name':"Maria",'age':24,'gender':'Female'}}

print(people[1]['name'])
print(people[1]['age'])
print(people[1]['gender'])

people = {1:{'name':"John",'age':25,'gender':'Male'},
          2:{'name':"Maria",'age':24,'gender':'Female'}}

people[3] = {}
people[3]['name'] = 'Luna'
people[3]['age'] = '24'
people[3]['gender'] = 'Male'
people[3]['married']= 'No'
print(people[3])

del people[3]['married']
print(people)


John
25
Male
{'name': 'Luna', 'age': '24', 'gender': 'Male', 'married': 'No'}
{1: {'name': 'John', 'age': 25, 'gender': 'Male'}, 2: {'name': 'Maria', 'age': 24, 'gender': 'Female'}, 3: {'name': 'Luna', 'age': '24', 'gender': 'Male'}}


In [32]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a)) #ndarray = n-dimensional array

[1 2 3]
<class 'numpy.ndarray'>


In [42]:
#A-range function
import numpy as np
a = np.arange(1,120,2)
print(a)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119]


In [52]:
#reshape function

import numpy as np
a = np.array([(1,2,3),(5,6,7)])
print(a)
a.reshape(3,2)


[[1 2 3]
 [5 6 7]]


array([[1, 2],
       [3, 5],
       [6, 7]])

In [53]:
#flatten Data

import numpy as np
a = np.array([(1,2,3),(5,6,7)])
print(a)
a.flatten()

[[1 2 3]
 [5 6 7]]


array([1, 2, 3, 5, 6, 7])

In [56]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [57]:
np.ones((2,2), dtype = complex)

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])

In [59]:
x = [1,2,3]
print(x)
print(type(x))

a = np.asarray(x)
print(a)
print(type(a))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [61]:
a = np.array([9,5,3,1,8,7])
print(np.sort(a))

[1 3 5 7 8 9]


In [62]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [65]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [68]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [71]:
#matrix multiplication

h = [[1,2],[3,4]]
i = [[5,6],[7,8]]
np.matmul(h,i)

array([[19, 22],
       [43, 50]])

In [ ]:
a 